!$AutonumStart = 5
!include __init__

title ORP Code Merge Flow - Late Addition After Merge Cutoff

== Scope Cutoff  ==

note over feature, release : After Scope Cutoff, you won't be able to add upcoming <b>Release Cycle</b> into your ticket anymore

== Merge Cutoff  ==

hnote over feature,release #Orange:Removal of <b>in-scope pending merge</b> tickets
hnote over master,staging #Orange:Auto-Merge **master** into **staging**
master -> staging: merge <b>master</b>\ninto <b>staging</b>

group 5.0 Late Merge Flow
    note over feature, staging : $late_justification
    hnote over feature,staging #Red:Any <b>low-priority</b> late request should follow <b>next Regular Release
    
    hnote over feature #LimeGreen: $if_RM_approves
    note over feature: MUST pass verifications
    
    feature -> staging: merge <b>feature</b>\ninto <b>staging</b>
end

== Staging Deployment Start  ==
