!$AutonumStart = 7
!include __init__

title ORP Code Merge Flow - Deployment Day

== Timing Depends on Service's RM-Categorised-Platform == 
hnote over release #DarkOrchid: Current LIVE\nversion: **V1.5.6**
hnote over staging,release #LimeGreen: RM Triggers\nAuto-Merge **staging** into **release**

hnote over release,staging #Orange:Auto-Merge **release** into **staging**
$staging_into_release
hnote over release #DarkOrchid: New tag generated\nversion: **V1.6.0**

group 7.0 Deployment Flow
    note over staging,release #LimeGreen: RM verifies no other blocker to release\nAND obtains dev PIC's acknowledgement to start

    hnote over staging,release#LimeGreen: RM executes deployment with **V1.6.0**

    hnote over release #DarkOrchid: Current LIVE\nversion: **V1.6.0**

end group
