@startuml
!theme bluegray
skinparam FooterFontColor black

title PreBuild Logic Diagram

start

:PreBuild is called, Data:\n- Service CMDB ID\n- ReleaseTag;

group Follow Up Previous Attempts
    if (Was there a SUCCESS PreBuild attempt?\n(GET stored pipeline ID)) then (TRUE)
        ' :Do NOT execute PreBuild;
        if (Build Status == SUCCESS) then ( )
            :Status code 0;
            stop
        elseif (Build Status == RUNNING) then ( )
            :Status code 1;
            stop
        else (else)
            ' :continue;
        endif
    else (FALSE)
    endif
end group

group Condition Check
    if (Does the CMDB service\nsupport separation of BUILD & DEPLOY?) then (FALSE)
        :Status code 2;
        stop
    else (TRUE)
        if (Does the CMDB service\nhost any cron jobs in LIVE?) then (TRUE)
            :Status code 3;
            stop
        else (FALSE)
        endif
    endif
end group

group Execute Build
    if (Reaches Max Retry?) then (TRUE)
        :Status code 5;
        stop
    else (FALSE)
    endif

    :Update DB `Attempt Count += 1`;
    if (Execute Build) then (FAILS)
        :Status code 4;
        stop
    else (SUCCESS)
        :Status code 1;
    endif
stop
end group


@enduml