@startuml
!theme bluegray
skinparam FooterFontColor black

title User Flow on Deployment Dashboard with PreBuild Assist

start

:In "Pending Deployment" state;
:User click action: Deploy;
:System GET PreBuild data w Arg:\n- Service CMDB ID\n- ReleaseTag;


if (PreBuild Status Code) then (0 - SUCCESS)
    
    group **PreBuild Assist**\nwith SUCCESS build
        :System prompts user;
        note left
            "Existing build for {version} detected,
            DEPLOY_ONLY will be pre-filled"

            1. Acknowledge
        end note
        :System popup normal Deploy prompt\nWith **FROM_BRANCH==tag**\n&& **DEPLOY_ONLY==TRUE**;
        :User can proceed normally;
        split
            :User exit;
            stop
        split again
            :User deploy without changing param FROM_BRANCH or DEPLOY_ONLY;
            :System execute deployment;
            stop
        split again
            :User change param\n- FROM_BRANCH\n- or DEPLOY_ONLY;
        end split
    end group
elseif (1 - WIP)
    group **PreBuild Assist**\nwith WIP build
        :System prompts user;
        note left
            "Existing build for {version} is WIP,
            Do you want to 

            1. Abort it and continue
            2. OR exit prompt and wait"
        end note
        if (User choose) then (1)
            :System abort existing PreBuild;
            :Close prompt;
        else (2)
            :Close both prompt and deployment window;
            stop
        endif
        :System popup\nnormal Deploy prompt;
    end group
else (2,3 - NA/Failed)
    :System popup\nnormal Deploy prompt;
endif

group **PreBuild Assist**\nwithout SUCCESS build
        
    :User can proceed normally;
    repeat
        split
            :User exit;
            stop
        split again
            if (User proceeds with deployment\nwith..) then (DEPLOY_ONLY==FALSE)
                :Normal\ndeploy execution;
                stop
            else (DEPLOY_ONLY==TRUE)
                group Checks Before\nDeployment Execution
                    if (GET PreBuild status with\n- CMDB ID\n- Release Tag) then (status == 0)
                        :Proceed with\ndeploy execution;
                        stop
                    elseif (status == 1)
                        group Abort WIP\nPreBuild Override
                            :- System GET PreBuild callback_id\n- System aborts the PreBuild pipeline\n- System initialise the full BUILD+DEPLOY pipeline;
                            stop
                        end group
                    else (Else other status)
                        :Error prompt\nto user;
                        note right
                            "No existing PreBuild
                            for selected tag"
                            
                            1. Acknowledge
                        end note
                    endif
                end group
            endif
        end split
    backward :User back\nto step before\ndeployment execution;
    repeat while (User ACK\nerror prompt)
end group

kill

@enduml