@startuml

!$AutonumStart = 3

!include __init__

group 3.0 Host Repository MERGE Cut-off
    RM -> Art: Executes\nfinal verifications

    == Friday 17:00 : Host repository Scope Cut-off ==
    note over req,RM#Tomato: Beyond this point:\n- Unverified tickets will be removed\n- Scope is locked down, requesters will be unable submit anymore into scope

    note over req,RM: During this period,\nDevs can still execute code merge for in-scope requests.

    Art -> Art: RPR merge IB\nverified HOST-repo MR
    RN_DOD -> Art: Merge CB\nverified HOST-repo MR

    hnote over Art#LimeGreen:<b>MERGED\n<b>SPFE MR

    == Monday 10:00 : RPR Late Submission Cutoff ==

    note over req,RM#Tomato: Beyond this point, late scope request will need ERA adhoc request

    == Monday 12:00 : Host repository Merge Cutoff ==

    note over req,RM#Tomato: Beyond this point:\n- In-Scope requests not yet merged will be REMOVED

end


@enduml
