!$AutonumStart = 4
!include __init__

title FE Regular Release Schedule

hnote over release #DarkOrchid: Current LIVE\nversion: **V1.5.5**

== Wednesday 16:30  ==
note over feature,release #LimeGreen: RM finalises scope of regular release for prebuild preparation 
group 4.0 Prebuild Preparation
    note over master,release: Sync upcoming version with live
    
    release->staging: merge **release** into **staging**
    note right #Coral
        <color #Yellow >**ORP CHANGE**</color>
        Instead of managing
        **release-backup** branch,
        keep **release** for releases,
        while using **staging**, to stage
    end note 

    hnote over staging#Thistle: Dev generate new minor tag\nin staging
    staging->staging
    hnote over staging #DarkOrchid: Upcoming Regular\nversion: **V1.6.0**
    note right #Coral
        <color #Yellow >**ORP CHANGE**</color>
        Dev DOD will generate tag 
        in **staging** instead of usual **release**
        Then prebuild using this tag
    end note 
    hnote over staging#Thistle: DOD prebuild **V1.6.0**
end group


autonumber inc A
group 5.0 Emergency Release Situation
    note over feature,release#Crimson: If emergency release occurs here

    note over feature: Raise respective SWP
    note right #Coral
        <color #Yellow >**ORP CHANGE**</color>
        In emergency release situation, use **release**
        as per normal
    end note 
    release->feature: branch out of **release**
    hnote over feature #Thistle: Dev execute fix
    note over feature: - SWP Approved\n- QA signed-off\n- MR reviewed
    feature->feature: Dev merge fix

    feature->release: merge **feature** into **release**

    hnote over release#Thistle: DOD generate new patch tag
    hnote over release #DarkOrchid: Emergency\nversion: **V1.5.6**
    hnote over release#LimeGreen: RM executes deployment with **V1.5.6**
    hnote over release #DarkOrchid: Current LIVE\nversion: **V1.5.6**

    autonumber inc A
    group 6.0 Include Emergency Scope in Regular Scope
        note over staging,release: **AFTER** verification of emergency release\nwe need to sync changes into upcoming regular version
        release->staging: merge **release** into **staging**
        note right #Coral
            <color #Yellow >**ORP CHANGE**</color>
            After emergency release, 
            merge **release**
            into **staging**
            to include scope 
            in regular deployment,
            then we will prebuild again
        end note 
        note over staging,release: This is to sync changes into upcoming regular version
        
        hnote over staging#Thistle: DOD generates new patch tag
        hnote over staging #DarkOrchid: Upcoming Regular\nversion: **V1.6.1**
        hnote over staging#Thistle: DOD prebuilds **V1.6.1**
        note over staging: Where time is limited, DOD can do this\n in parallel with steps in **5.0**
    end group
end group
