@startuml
!theme bluegray
skinparam FooterFontColor black
skinparam DatabaseFontColor #007faf
skinparam ClassFontColor black
skinparam ClassBackgroundColor #d2d2d2


title Lean Functional Entity Relationships v4

class "<b>Team" as team {
    teamID
}

class "<b>Release Version" as version {
    versionID
    versionNumber
    versionStages
    versionDependency
}

class "<b>Change Request" as CR {
    CR_ID
    ChangeType
    Sub-Team
}

' class "<b>JiraTicket" as JIRA {
'     issueKey
' }

' class "<b>Sub-Team" as subTeam {
'     teamID
'     ---
'     In DB, team & subTeam is sharing same table
' }

class "<b>ReleaseProcess" as process {
    processName
    applicableSubTeams
}

class "<b>Service" as service {
    CMDB_ID
}

' class "<b>Release Checklist" as RC {
' }

' class "<b>Merge Request" as MR {
'     MR_ID
' }

class "<b>Repository" as Repo {
    repoPath
    projectID
}

class "<b>Workflow" as Workflow {
    workflowName
    releaseType
    versionStages
    supportedChangeTypes
    gitVerification (KIV)
    deploymentWorkflow (KIV)
}

class "<b>JiraVerification" as JiraVeri {
    verifications
    applicablSubTeams
}

class "<b>RegressionSchedule" as RegrScope {
        scopeID
}

' class "<b>RegressionTask" as RegrSched {
'         TaskName
'         Team
'         WorkflowCovered
' }

' class "<b>[NEW Entity] ReadinessCheckOperation" as ReadinessOps {
'     new DB TBC: shopee_deployplatform_db.readiness_check_operations_tab

'     Attributes:
'     - readiness_check_id
'     - deployment_request_id
'     - display_name
'     - default_pics
'     - toggle_timestamp
'     - toggle_author
'     ---
'     <b> NEW Function Requirements:
'     - GET ReadinessCheckOps
'     - Update ReadinessCheckOps
'     - Delete ReadinessCheckOps
' }

' class "<b> Service" as Service {
'     Attributes:
'     - CMDB ID
'     ---
'     <b> NEW Function Requirements:
'     - GET ReadinessCheckOperations
' }

' class "<b>[NEW Entity] Readiness Config" as ReadinessConfig {
'     ---
'     Attributes:
'     - active
' }

version "n" -down-* "1" team
' subTeam "n" -up-> "1" team
' version "1" -left-> "1" subTeam
' CR "n" -up-> "1" subTeam
CR "n" -left-o "1" version
' JIRA "1" -up-> "1" CR
' MR "1" -right-> "1" JIRA
' MR "1" -up-> "1" Repo
' RC "1" -up->  "1" JIRA
' service "n" -right-> "1" RC
service "n" -left-* "1" Repo
' RegrScope "n" -left-> "1" team
' RegrScope "1" <-left- "n" RegrSched

' version "n" <-- "1" RegrSched
' team "1" <-- "n" RegrSched
Repo "n" -up-o "1" team

' process "1   " <.right. "1" version
Workflow "1   " <-right- "n" version
Workflow "2   " -down-* "1" process
' process "1   " o-down- "n" Repo
process "n   " -right- "n" team
Workflow "1" -left-> "1" RegrScope
' process "n" .down.> "n" RegrScope


team "1   " -right- "1" JiraVeri

' CR "1   " -[dashed]down- "1" JiraVeri

' DS "1" *-- "0..*" DR 
' DR "1" *-- "0..*" ReadinessOps
' ReadinessOps "0..*" -up-* "1" Readiness
' Service "1" -left- "1" ReadinessConfig
' ReadinessConfig "1" -- "1" Readiness
' Service "1" --> "0..*" DR


@enduml
