@startmindmap

!theme bluegray
skinparam FooterFontColor black
skinparam DatabaseFontColor #007faf
skinparam ClassFontColor black
skinparam ClassBackgroundColor #d2d2d2

title Sample Release Process Instance V3

legend right
As of 4 Dec 2023
endlegend

* Team
** MP Release Process\n(CodeChange)
*** RegWorkflow
**** Stage_1
**** Stage_2
**** Stage_3
**** Stage_4

*** ER WkFlow
**** Stage_1
**** Stage_2
**** Stage_3


** CUSTOM Release Process\n(CodeChange)
*** RegWorkflow
**** Stage_1
**** Stage_2
**** Stage_3

*** ER WkFlow
**** Stage_1
**** Stage_2

** MP Config Process\n(ConfigChange)
*** Reg WkFlow
**** Stage_1
**** Stage_2
**** Stage_3
**** Stage_4
**** Stage_5
*** ER WkFlow
**** Stage_1
**** Stage_2

@endmindmap