@startmindmap
title Promotion Team Division

* Promotion L2
** SubTeam L3
*** "component" L4
**** CMDB Service
**** CMDB Service
*** "component" L4
**** CMDB Service
**** CMDB Service
*** "component" L4
**** CMDB Service
**** CMDB Service
** SubTeam L3
*** "component" L4
**** CMDB Service
**** CMDB Service
*** "component" L4
**** CMDB Service
**** CMDB Service
*** "component" L4
**** CMDB Service
**** CMDB Service

@endmindmap
