@startuml

!$AutonumStart = 3
!include __init__

title Regression Bug Flow

== Regular Release Merge Cut-Off (Usually Monday 17:00) ==

hnote over staging #DarkOrchid: Upcoming version\nV1.6.0

group Regression Bug Flow
    note over FB, staging : Regression Bug Flow fix is ONLY for bugs found in STAGING.\nQA lead has to certify by adding <b><color #black>SZ/SG_QA_Regression</color></b>
    staging -> FB: NEW branch out of <b>staging</b>
    FB -> FB: commit into\n<b>feature</b>
    FB -> staging: merge <b>feature</b> into <b>staging</b>
    hnote over staging #DarkOrchid:New Tag\n+patch\nV1.6.1
    staging -> host_staging: Build version,\nand bump version in host repo
end

hnote over host_staging #DarkOrchid: Upcoming\nplugin version\nV1.6.1

group Late Merge Flow
    note over FB, release : Late merge have to have justifiable reason.\nApproach RM justifying why this late scope need to be added into regular release.
    note over FB, staging : After RM approves, RM will add <b>Release Cycle</b> in SPFE
    FB -> staging: merge <b>feature</b> into <b>staging</b>
    hnote over staging #DarkOrchid:New Tag\n+patch\nV1.6.2
    staging -> host_staging: Build version,\nand bump version in host repo
end

hnote over host_staging #DarkOrchid: Upcoming\nplugin version\nV1.6.2

== Regular Release Release Pre-Build (Usually Wed 17:30) ==

@enduml
