@startuml

!$AutonumStart = 3
!include __init__

title Regression Bug Flow

== Regular Release Merge Cut-Off (Usually Monday 12:00) ==

host_master -> host_staging: Branch merge\nexecuted

hnote over staging #DarkOrchid: Upcoming version\nV1.6.0

group Regression Bug Flow
    note over FB, staging : Regression Bug Flow fix is ONLY for bugs found in STAGING.\nQA lead has to certify by adding <b><color #black>SZ/SG_QA_Regression</color></b>
    staging -> FB: NEW branch out of <b>staging</b>
    FB -> FB: commit into\n<b>feature</b>
    FB -> staging: merge <b>feature</b> into <b>staging</b>
    hnote over staging #DarkOrchid:New Tag\n+patch\nV1.6.1
    staging -> host_staging: Build version,\nand bump version in host repo
    note left
        For IB Plugin using RPR
        Select **Regular** type
        & **Regression** sub-type
    end note
end

== Regular Release Release Pre-Build (Usually Wed 17:30) ==

@enduml
