@startuml

title Deployment SOP Diagram

start

partition "RM select scope of deployment" {

#LightGreen:RM choose scope of current deployment;

if (Multiple jobs if requested by same devs) then (TRUE)
    #LightGreen:Rearrange jobs that are done together to be within adjacent rows;
    note left
        To optimise RM-Dev communication
    end note
    #Yellow:Consider the multiple rows as scope of deployment<
else (FALSE)
    #Yellow:Consider the single row as scope of deployment<
endif

#LightGreen:Update selected row(s) color to Yellow;
note left
    In DSG, we have shortcut for coloring rows
    CMD+option+Shift+2 : turn selected cells YELLOW to indicate WIP
end note 

#LightGreen:Copy col A,B,C (Job Name, PICs, IssueKeys) 
from DSG for the job to be deployed;
note left
    If parameter is crucial, also include col D
end note

#LightGreen:Start a new thread in deployment channel,
Paste copied columns into thread and ask:
"Shall we start deployment?";
note left
    To signal to dev that we want to start deployment.
end note

repeat
    #LightGreen:Follow up with devs for Ack every 15 mins ;
repeat while (<back:lightblue>All Dev PICs Acknowledged start of deployment?</back>) is (No)
}

partition "RM Deployment SOP" {
repeat
    partition "Triggering Deployment" {
    #LightGreen:Trigger start of deployment according to requested params;
    #LightGreen:Informs dev:
    Deploying {Service} in {Regions};
    note left
        In DSG, we have shortcut for coloring rows
        option+enter : Open all url in selected cells in a new tab
    end note 
    }

    partition "Deployment Follow Up" {
    repeat
        #LightGreen:Follow up build status;
    repeat while (Build is done?) is (No)

    if (Deployment Failure) then
        partition "Deployment Failure Case" {
        #LightGreen:In the same MM Thread,
        Inform dev with the format
        Hi {dev_pic}, 
        facing error in {console_URL},

        please help to check: 
        
        {snippet of error if RM able to identify};
        note left
            If Error is due to BUILD/JENKINS
            We will need to involve SRE,
            Check SRE on duty for service from Service-CMDB
            And @ him in the MM thread
        end note
    
        repeat
            #LightGreen:Follow up with dev if issue is resolved;
        repeat while (<back:lightblue>Issue resolved?</back>) is (No)
        }
    elseif (Deployment Success)
        partition "Deployment Success Case" {
        #LightGreen:In the same MM Thread,
        Inform devs with the format
        Hi {dev_pic}, deployment of {Service} is done in {Regions},
        Please help to verify in live;
    
        repeat
            #LightGreen:Follow up with dev if LIVE deployment is verified;
        repeat while (<back:lightblue>LIVE deployment verified?</back>) is (No)
        }
    elseif (Canary is Up)
        partition "Deployment Canary Case" {
        repeat
            :Next batch of Canary is Up for verification;
            #LightGreen:In the same MM Thread,
            Inform devs with the format
            Hi {dev_pic}, canary of {Service} is up in {Regions},
            Please help to verify canary instances;

            repeat
                #LightGreen:Follow up with dev if canary verified;
            repeat while (<back:lightblue>Canary verified?</back>) is (No)

            #LightGreen:Promote canary;
            repeat
                #LightGreen:Follow up if all instances are up;
            repeat while (All instances up?) is (No)

        repeat while(All canary stages Done?) is (No)

        #LightGreen:In the same MM Thread,
        Inform devs with the format
        Hi {dev_pic}, deployment of {Service} is done in {Regions},
        Please help to verify in live;

        repeat
            #LightGreen:Follow up with dev if LIVE deployment is verified;
        repeat while (<back:lightblue>LIVE deployment verified?</back>) is (No)
        }
    elseif (Deployment Stuck Due to Resources)
        partition "Deployment Resource Stuck Case" {
        repeat
            #LightGreen:Wait;
        repeat while(Still stuck in the last 15 mins?) is (Yes)
        #LightGreen:Find SRE pic for the affected service via Service-CMDB detail page.
        Ping the SRE pic in MM Thread as such
        
        Hi {SRE dev pic}, we are facing deployment resource issue in {console URL to service}.
        May I know if we can clear up some resources? This is currently blocking LIVE deployment.
        
        Thanks;
    
        repeat
            #LightGreen:Follow up with SRE OR observe deployment progress;
        repeat while(Deployment is Progressing?) is (No)

        :Continue from applicable status above;
        stop
        }
    elseif (Dev/NOC raised issue and request rollback)
        partition "Deployment Rollback Case" {
        #LightGreen:Identify the last stable tag via JENKINS history OR Service-CMDB;
        #LightGreen:Execute rollback;
        #LightGreen:Follow up with dev for
        - Root cause
        - Resolution
        - Expected deployment continuation plan;
        :For more details, see <b>Rollback SOP</b> below;
        stop 
        }
    else
        #Pink:Unknown corner case;
        stop
    endif
    }

repeat while(All Deployment for current scope is finished?) is (No)

#LightGreen:Update DSG row colow to Green;
note left
    In DSG, we have shortcut for coloring rows
    CMD+option+Shift+3 : turn selected cells GREEN to indicate DONE
end note 
}

if (ALL deployments done) then (TRUE)
    :End of deployment;
    stop
else (FALSE)
    :Start again from beginning;
    stop
endif

@enduml