@startuml
!theme bluegray
skinparam FooterFontColor black
skinparam StateFontColor black

state "Pending Dev Ack(PreOp)" as pendingDevAckPreOp
state "Pending Dev Ack" as pendingDevAck

title State Flow Diagram\n- Status Quo

[*] --> pendingDevAckPreOp : InitSequence
pendingDevAckPreOp --> pendingDevAck : Start operation
pendingDevAckPreOp: RM: Start Operation

pendingDevAck: Dev: ACK
pendingDevAck --> [*] : To further state

@enduml