@startuml
!theme bluegray
skinparam FooterFontColor black
skinparam StateFontColor black

state "Pending Start Operation" as preOp
state "Pending Dev Ack" as pendingDevAck
state "Pending Readiness Check" as pendingReadiness

title State Flow Diagram\n- Changes Only

[*] --> preOp : InitSequence
note right of preOp : [CHANGED]\n- new inert status\n- REMOVE dev noti\n  on start operation
preOp: RM: Start Operation

note right of pendingReadiness : [CHANGED] \n- new status\n- new check
preOp --> pendingReadiness : Start operation

pendingReadiness --> pendingDevAck : All events passed
pendingReadiness: System: Check for event whitelist

note right of pendingDevAck : [CHANGED]\n- ADD dev noti\n  on start operation
pendingDevAck: Dev: ACK
pendingDevAck --> [*] : To further state

@enduml