@startuml
!theme bluegray
skinparam FooterFontColor black
skinparam DatabaseFontColor #007faf

entity Signoff as Signoff
entity DeploymentDashboard as DD
participant ReleaseEngine as RE
database gitlab_project_tab as gitDB
' database deployment_request_tab as deploymentDB
database deployment_ack_config_tab as ackDB
database pre_release_events_tab as PREDB

title Pending Pre-Release Events Behaviour

== for each deployment request in Deployment Sequence ==
group Initialisation
    RE -> ackDB : with jenkins_job\nGET <b>repo
    ackDB -> RE : repo
    
    RE -> gitDB : with repo\nGET requires_regression_signoff
    
    gitDB -> RE : requires_regression_signoff

    RE -> PREDB : For each configured PreRelease Event\nInitialise an entry
    
    group If no pre_release_events
        RE -> RE : Trigger state update
    end group
end group

    PREDB -> DD : Display events in popup
    note right
        when user hover over the status
        Pending pre-release events
        the list of pre-release events 
        should be displayed
    end note


group Pending Dev Ack Transitions
    group via external API
        Signoff -> RE : Toggle state via RE API
        RE -> PREDB : DB toggle handler\nwith key & state
        PREDB -> PREDB : Update\n- key\n- state\n- date
        RE -> RE : Trigger state update
    end group
    group via Dashboard UI
        DD -> RE : Via button
        RE -> PREDB : DB toggle handler\nwith key & state
        PREDB -> PREDB : Update\n- key\n- state\n- date
        RE -> RE : Trigger state update
    end group
end group

group State Update
    RE -> PREDB : GET pre_release_blockers
    PREDB -> RE : pre_release_blockers

    group If ALL event state == True
        RE -> RE
        note right
            transition to next state
        end note
    end group 
    group else
        RE -> RE
        note right
            pass
        end note
    end group            
end group

' (*) --> [Enter State] Initialisation

' --> Get row's repo path
' --> [with repo path] Get config data for required events

@enduml