@startuml
!theme bluegray
skinparam FooterFontColor black
skinparam DatabaseFontColor #007faf
skinparam ClassFontColor black
skinparam ClassBackgroundColor #d2d2d2


title Relationship Between DeploymentSequence - DeploymentRequest - ReadinessCheck

class "<b>DeploymentSequence" as DS {
    current DB: shopee_deployplatform_db.deployment_seq_tab
}
class "<b>DeploymentRequest" as DR {
    current DB : shopee_deployplatform_db.deployment_request_tab

    NEW Function Requirements:
    - Initialise PreReleaseEvents
    - GET PreReleaseEvents
}

class "<b>[NEW Entity] PreReleaseEvent" as PRE {
    Attributes:
    - pre_release_event_id
    - display_name
    - default_pics
    
    NEW Function Requirements:
    - GET PreReleaseEvent
    - Toggle PreReleaseEvent
}

DS "1" *-- "many" DR 
DR "1" *-- "many" PRE

@enduml
