@startuml
!theme bluegray
skinparam FooterFontColor black
skinparam DatabaseFontColor #007faf
skinparam ClassFontColor black
skinparam ClassBackgroundColor #d2d2d2


title Relationship Between DeploymentSequence - DeploymentRequest - ReadinessCheck

class "<b>DeploymentSequence" as DS {
    current DB: shopee_deployplatform_db.deployment_seq_tab
    ---
    <b> NEW Function Requirements:
    - Get ReadinessCheckOperations per services 
}
class "<b>DeploymentRequest" as DR {
    current DB : shopee_deployplatform_db.deployment_request_tab
    ---
    <b> NEW Function Requirements:
    - Initialise ReadinessCheckOps
    - GET ReadinessCheckOps
    - Transition next state when ReadinessCheckOps pass
    - Override next state
}

class "<b>[NEW Entity] ReadinessCheck" as Readiness {
    new DB TBC: shopee_deployplatform_db.readiness_checks_tab

    Attributes:
    - readiness_check_id
    - display_name
    - default_pics
    ---
    <b> NEW Function Requirements:
    - GET ReadinessChecks
    - Update ReadinessCheck
    - Delete ReadinessCheck
    - Init new ReadinessCheck
}

class "<b>[NEW Entity] ReadinessCheckOperation" as ReadinessOps {
    new DB TBC: shopee_deployplatform_db.readiness_check_operations_tab

    Attributes:
    - readiness_check_id
    - deployment_request_id
    - display_name
    - default_pics
    - toggle_timestamp
    - toggle_author
    ---
    <b> NEW Function Requirements:
    - GET ReadinessCheckOps
    - Update ReadinessCheckOps
    - Delete ReadinessCheckOps
}

class "<b> Service" as Service {
    Attributes:
    - CMDB ID
    ---
    <b> NEW Function Requirements:
    - GET ReadinessCheckOperations
}

class "<b>[NEW Entity] Readiness Config" as ReadinessConfig {
    ---
    Attributes:
    - active
}


DS "1" *-- "0..*" DR 
DR "1" *-- "0..*" ReadinessOps
ReadinessOps "0..*" -up-* "1" Readiness
Service "1" -left- "1" ReadinessConfig
ReadinessConfig "1" -- "1" Readiness
Service "1" --> "0..*" DR
@enduml
