@startuml
!theme bluegray


title Proposed Data Flow

split
    hidden
    start
    :service_id;
split again
    start
    :service_name;
split again
    start
    :pipeline_name;
end split




@enduml
